### ISSUE TITLE
6.6 saltstack学习资源汇总

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/iBlog#291]
镜像问题

## 2018.1.9 ansible 学习资源汇总
https://github.com/vieyahn2017/iBlog/issues/8

**Comment by vieyahn2017** [comment]
开源自动化配置管理工具ansible、saltstack、Puppet、Chef选择
http://blog.csdn.net/yujin2010good/article/details/56489560

Ansible vs SaltStack 谁才是自动化运维好帮手？
http://blog.csdn.net/a105421548/article/details/53558598

**Comment by vieyahn2017** [comment]
http://blog.csdn.net/qq_21398167/article/details/52610531
自动化运维工具SaltStack详细部署

csdn的博客主： 傻呆
有运维，有Openstack，prometheus，QT等

**Comment by vieyahn2017** [comment]
## 自动化运维工具saltstack详解

https://blog.csdn.net/llllyr/article/details/103472874?depth_1-utm_source=distribute.pc_relevant.none-task&utm_source=distribute.pc_relevant.none-task


### 文章目录
saltstack详解
saltstack简介
什么是zmq消息队列？
与其他自动化管理工具对比
服务端口
salt的安装与部署
salt配置路径
数据存放
.sls文件语法
saltstack任务简单示例

**Comment by vieyahn2017** [comment]
saltstack简介
Saltstack是基于Python开发的一套C/S架构，具备Puppet、Ansible功能于一身的配置管理工具，功能十分强大，各模块融合度及复用性极高；使用号称世界上最快的消息队列ZeroMQ使得Saltstack能够秒级在数万台服务器上进行各种操作，而且使用RAS Key方式确认身份，传输采用AES加密，安全性能更高；

Saltstack不仅仅是一款配置管理工具，还是一款做云计算和数据中心架构编排利器。目前Salt-cloud项目也已经合并到Saltstack主项目里，Saltstack已经支持Docker相关模块，在友好地支持各大云平台之后，配合Saltstack的Mine实现各云平台业务自动扩展。

saltstack的核心特点：

使用命令发送到远程系统是并行的而不是串行的

使用安全加密的协议

使用最小最快的网络载荷 提供简单的编程接口，设备轻量级

SaltStack作用于仆从和主拓扑。SaltStack与特定的命令结合使用可以在一个或多个下属执行

**Comment by vieyahn2017** [comment]
yum install -y salt-master salt-minion
安装服务端 客户端


授权处理
授权命令salt-key 常用参数

参数 | 作用
-- | --
-L | 查看授权列表
-A | 对所有主机授权
-a | 指定主机授权



查看master端授权信息列，可以看到已有可授权主机出现

[root@server1 yum.repos.d]# salt-key -L
```

Accepted Keys:
Denied Keys:
Unaccepted Keys:
server2
server3
Rejected Keys:
```

对salt-minion端授权
salt-key -A

**Comment by vieyahn2017** [comment]
### salt连通测试：

利用test.ping （test模块下的ping方法）测试连通性
salt server? test.ping  ##表示测试server所有主机
或者测试指定主机
salt server1 test.ping

**Comment by vieyahn2017** [comment]
### .sls文件语法
（1）.sls文件本质上是python嵌套字典(键值对)，由salt-master以广播的形式传递给salt-minion，通过sls文件告知使用哪个模块的哪个函数，参数有哪些，在salt-minion一侧进行函数调用

（2）冒号’:’ 用来分隔键和值， 冒号：与后面的单词如果在一行，一定要有一个空格， 一个单词后面是否有冒号：取决于这个单词是否是key, 后面是否有值或者是嵌套的内容

（3）短横杠 - 表示这项是个列表项， 短横杠与后面的单词有一个空格

（4）缩进： 本层与下一层要有缩进， 缩进不能用tab, 一般是两个空格. 相同的缩进表示相同的层级

### saltstack任务简单示例
以apache服务的部署为例
[root@server1 salt]# pwd
/srv/salt
[root@server1 salt]# mkdir apache  ##创建任务角色
[root@server1 salt]# cd apache/
[root@server1 apache]# pwd
/srv/salt/apache
[root@server1 apache]# vim apache.sls  ##编写.sls任务
```
apache-install: ##唯一性声明
  pkg.installed: ##调用模块
    - pkgs:
      - httpd-tools
      - httpd
  file.managed:  ##配置文件修改
    - name: /etc/httpd/conf/httpd.conf
    - source: salt://apache/files/httpd.conf

  service.running:
    - name: httpd
    - reload: true
    - watch:  ##检测这项任务是否发生改变 发生改变reload服务
      - file: apache-install
```

或者

[root@server1 apache]# vim apache.sls 
```
apache-install: ##唯一性声明
httpd:
  pkg.installed ##调用模块
```
saltstack中的sls写法比较灵活，两种方式都是可以的


执行推送：

[root@server1 apache]# salt server3 state.sls apache.apache
